apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: secondary-scheduler-serving-cert
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    app: secondary-scheduler
  name: metrics
  namespace: openshift-secondary-scheduler-operator
spec:
  ports:
  - name: https
    port: 10259
    protocol: TCP
    targetPort: 10259
  selector:
    app: secondary-scheduler
  sessionAffinity: None
  type: ClusterIP
