apiVersion: v1
kind: ConfigMap
metadata:
  name: "TargetLoadPacking"
  namespace: "openshift-secondary-scheduler-operator"
data:
  "config.yaml": |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: secondary-scheduler
        plugins:
          score:
            disabled:
              - name: NodeResourcesBalancedAllocation
              - name: NodeResourcesLeastAllocated
            enabled:
              - name: TargetLoadPacking
        pluginConfig:
          - name: TargetLoadPacking
            args:
              defaultRequests:
                cpu: "2000m"
              defaultRequestsMultiplier: "1"
              targetUtilization: 70
              metricProvider:
                type: Prometheus
                address: ${PROM_URL}
                token: ${PROM_TOKEN}
